[package]
name = "test_util"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tikv_util = { path = "../tikv_util" }
tikv_alloc = { path = "../tikv_alloc", default-features = false }
time = "0.1"
rand = "0.5"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
