[package]
name = "sst_importer"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
crc = "1.8"
futures = "0.1"
grpcio = { version = "0.5.0-alpha.3", features = [ "openssl-vendored" ] }
lazy_static = "1.3"
quick-error = "1.2.2"
serde = "1.0"
serde_derive = "1.0"
tokio-sync = "0.1.7"
uuid = { version = "0.7", features = [ "serde", "v4" ] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
kvproto = { git = "https://github.com/zhangjinpeng1987/kvproto.git", branch = "cold-hot-separator" }
engine_traits = { path = "../engine_traits" }
engine = { path = "../engine" }
keys = { path = "../keys" }
tikv_alloc = { path = "../tikv_alloc", default-features = false }
external_storage = { path = "../external_storage" }
hex = "0.3"

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "7dd3d42f0c21384950afe6a46ed85352acf71625"
default-features = false

[dev-dependencies]
tempfile = "3.0"
test_sst_importer = { path = "../test_sst_importer" }
