[package]
name = "tikv"
version = "2.1.0-rc.2"
keywords = ["KV", "distributed-systems", "raft"]
publish = false

[features]
default = []
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]
mem-profiling = ["jemallocator"]
no-fail = ["fail/no_fail"]

[lib]
name = "tikv"

[[bin]]
name = "tikv-server"

[[bin]]
name = "tikv-ctl"

[[bin]]
name = "tikv-importer"

[[bench]]
name = "raftstore"
harness = false

[[bench]]
name = "benches"

[dependencies]
log = { version = "0.3", features = ["release_max_level_debug"] }
slog = "2.3"
slog-async = "2.3"
slog-scope = "4.0"
slog-stdlog = "3.0.4-pre"
slog-term = "2.4"
byteorder = "1.2"
rand = "0.3"
quick-error = "1.2.2"
tempdir = "0.3"
time = "0.1"
toml = "0.4"
libc = "0.2"
crc = "1.8"
fs2 = "0.4"
protobuf = "~2.0"
nix = "0.11"
utime = "0.2"
chrono = "0.4"
chrono-tz = "0.5"
lazy_static = "0.2.1"
backtrace = "0.2.3"
clap = "2.32"
url = "1.5"
regex = "1.0"
fnv = "1.0"
sys-info = "0.5.1"
indexmap = { version = "1.0", features = ["serde-1"] }
mio = "0.5"
futures = "0.1"
futures-cpupool = "0.1"
tokio-core = "0.1"
tokio-timer = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
zipf = "0.2.0"
bitflags = "1.0.1"
fail = "0.2"
uuid = { version = "0.6", features = [ "serde", "v4" ] }
grpcio = { version = "0.4", features = [ "secure" ] }
raft = "0.3"
crossbeam-channel = "0.2"
crossbeam = "0.2"
fxhash = "0.2"
derive_more = "0.11.0"
num = "0.2.0"
hex = "0.3"
rust-crypto = "^0.2"
panic_hook = { path = "components/panic_hook" }

[replace]
"raft:0.3.1" = { git = "https://github.com/pingcap/raft-rs.git" }

[dependencies.murmur3]
git = "https://github.com/pingcap/murmur3.git"

[dependencies.rocksdb]
git = "https://github.com/zhangjinpeng1987/rust-rocksdb.git"
branch = "compaction-reason"

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto.git"

[dependencies.tipb]
git = "https://github.com/pingcap/tipb.git"

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["nightly", "push", "process"]

[dependencies.prometheus-static-metric]
version = "0.1.4"

[dependencies.jemallocator]
git = "https://github.com/busyjay/jemallocator.git"
branch = "dev"
features = ["profiling"]
optional = true

[dev-dependencies]
test_util = { path = "components/test_util" }
test_raftstore = { path = "components/test_raftstore" }
test_storage = { path = "components/test_storage" }
test_coprocessor = { path = "components/test_coprocessor" }
criterion = "0.2"
arrow = "0.10.0"

[target.'cfg(unix)'.dependencies]
signal = "0.6"

[workspace]
members = [
  "fuzz",
  "components/test_raftstore",
  "components/test_storage",
  "components/test_coprocessor",
  "components/test_util",
  "components/codec",
  "components/panic_hook",
]

[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`
codegen-units = 4

# The release profile, used for `cargo build --release`
[profile.release]
lto = true
opt-level = 3
debug = true
# TODO: remove this once rust-lang/rust#50199 and rust-lang/rust#53833 are resolved.
codegen-units = 1

# The benchmark profile is identical to release, except that lto = false
[profile.bench]
lto = false
opt-level = 3
debug = true
codegen-units = 1
