[package]
name = "tidb_query"
version = "0.0.1"
edition = "2018"
publish = false
description = "A query engine to run TiDB pushed down executors"

[dependencies]
failure = "0.1"
byteorder = "1.2"
rand = "0.6.5"
rand_xorshift = "0.1.1"
regex = "1.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = "0.4"
chrono-tz = "0.5.1"
lazy_static = "1.3"
num = { version = "0.2", default-features = false }
num-traits = "0.2"
hex = "0.3"
base64 = "0.10"
twoway = "0.2.0"
ordered-float = "1.0"
nom = "5.0.0-beta1"
servo_arc = "0.1.1"
bitfield = "0.13.2"
protobuf = "2"
openssl = { version = "0.10" }
crc = "1.8"
time = "0.1"
quick-error = "1.2.2"
bitflags = "1.0.1"
derive_more = "0.15.0"
smallvec = "0.6"
indexmap = { version = "1.0", features = ["serde-1"] }
safemem = { version = "0.3", default-features = false }
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tipb = { git = "https://github.com/pingcap/tipb.git" }
kvproto = { git = "https://github.com/zhangjinpeng1987/kvproto.git", branch = "cold-hot-separator" }

tipb_helper = { path = "../tipb_helper" }
tikv_util = { path = "../tikv_util" }
match_template = { path = "../match_template" }
tidb_query_datatype = { path = "../tidb_query_datatype" }
tidb_query_codegen = { path = "../tidb_query_codegen" }
codec = { path = "../codec" }

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "7dd3d42f0c21384950afe6a46ed85352acf71625"
features = ["nightly", "push", "process"]

[dev-dependencies]
profiler = { path = "../profiler" }
panic_hook = { path = "../panic_hook" }
