[package]
name = "cmd"
version = "0.0.1"
license = "Apache-2.0"
edition = "2018"
publish = false
default-run = "tikv-server"

[features]
default = ["tikv/default"]
tcmalloc = ["tikv/tcmalloc"]
jemalloc = ["tikv/jemalloc"]
mimalloc = ["tikv/mimalloc"]
portable = ["tikv/portable"]
sse = ["tikv/sse"]
mem-profiling = ["tikv/mem-profiling"]
profiling = ["tikv/profiling"]
failpoints = ["tikv/failpoints"]

[lib]
name = "cmd"

[[bin]]
name = "tikv-server"

[[bin]]
name = "tikv-ctl"

[dependencies]
tikv = { path = "../", default-features = false }
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
rand = "0.7"
toml = "0.4"
libc = "0.2"
fs2 = "0.4"
protobuf = "2"
nix = "0.11"
chrono = "0.4"
clap = "2.32"
url = "2"
futures = "0.1"
serde = "1.0"
serde_json = "1.0"
fail = "0.3"
grpcio = { version = "0.5.0-alpha.3", features = [ "openssl-vendored" ] }
raft = "0.6.0-alpha"
hex = "0.3"
vlog = "0.1.4"
kvproto = { git = "https://github.com/zhangjinpeng1987/kvproto.git", branch = "cold-hot-separator" }
tikv_util = { path = "../components/tikv_util" }
engine = { path = "../components/engine" }
pd_client = { path = "../components/pd_client" }
backup = { path = "../components/backup" }

[target.'cfg(unix)'.dependencies]
signal = "0.6"
