[package]
name = "engine_rocks"
version = "0.0.1"
edition = "2018"
publish = false

[features]
jemalloc = ["rocksdb/jemalloc"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]
update_titan = ["rocksdb/update_titan"]

[dependencies]
kvproto = { git = "https://github.com/zhangjinpeng1987/kvproto.git", branch = "cold-hot-separator" }
protobuf = "2"
raft = "0.6.0-alpha"
quick-error = "1.2.2"
crc = "1.8"
lazy_static = "1.3"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
time = "0.1"
sys-info = "0.5.7"
tikv_alloc = { path = "../tikv_alloc" }
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
hex = "0.3"
tikv_util = { path = "../tikv_util" }
engine = { path = "../engine" }
engine_traits = { path = "../engine_traits" }

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "7dd3d42f0c21384950afe6a46ed85352acf71625"
features = ["nightly", "push", "process"]

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
package = "rocksdb"

[dev-dependencies]
tempfile = "3.0"
