[package]
name = "test_raftstore"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
tikv_util = { path = "../tikv_util" }
tikv = { path = "../../", default-features = false }
kvproto = { git = "https://github.com/zhangjinpeng1987/kvproto.git", branch = "cold-hot-separator" }
protobuf = "2"
tempfile = "3.0"
raft = "0.6.0-alpha"
futures = "0.1"
tokio-timer = "0.2"
tokio-threadpool = "0.1"
grpcio = { version = "0.5.0-alpha.3", features = [ "secure" ] }
rand = "0.7"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
engine = { path = "../engine" }
hex = "0.3"
pd_client = { path = "../pd_client" }
